### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by cdkonecny** [csdozier/device-concord4#10]
Set notifications to only be sent a particular mode, like 'AWAY.' When ST not in that mode, rather than not firing notifications, the device states actually stop updating outside of Concord4 Smartapp.   Depending on use case, this could affect ability to use sensors for automations outside of security monitoring.   Noting this to help anyone else as it wasn't clear as to why the device states all appeared frozen.

**Comment by csdozier** [comment]
Can you explain how you set notifications to be this way?

**Comment by cdkonecny** [comment]
At the very bottom of the Smartapp settings where it says "Set for specific modes"

**Comment by csdozier** [comment]
Ok, so I never tested this, but I would say its expected.  The smartapp is
used to update the device states of the virtual devices, that it's purpose.

**Comment by cdkonecny** [comment]
That makes sense, just wanted to call it out in case it helps anyone else 
scratching their head.  It was a little confusing since that option is 
grouped under notification settings.    Great app, btw, I finally have 
everything working 100% with great integration with Smart Home Monitor.   
Very much appreciated!
