### ISSUE TITLE
encoding bug?

### ISSUE THREAD

**Issue by rwa** [csdozier/device-concord4#6]
I think you inherited a fairly major bug from py-concord here.

def encode_message_to_ascii(bin_msg):
    s = ''
    for b in bin_msg:
        s += '%02x' % b
    return s

The protocol only accepts upper case for the hex encoding in ascii.  But python returns lower case.  This can affect checksums in particular.

"return s.upper()" should do the trick.

**Comment by csdozier** [comment]
Thanks , I will test it out

**Comment by rwa** [comment]
I wasn't affected by this by sheer luck I think until I was testing the following command for "arm silently":

06 40 01 00 05 21 6D

the checksum was being sent as "6d" and it wasn't working.  I was able to isolate this by sending data directly using echo:

echo -en '\n0640010005216D' > /dev/ttyUSB0 worked
echo -en '\n0640010005216d' > /dev/ttyUSB0 didn't work

**Comment by rwa** [comment]
Fixed
